name: Ba-dua

on:
  push:
    branches: [ testing-exam ]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      # Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Java 18
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18

      # Cache Maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Clone e build del repository di Ba-dua
      - name: Clone and build ba-dua repository
        run: |
          git clone https://github.com/saeg/ba-dua
          cd ba-dua
          git checkout d2401f0
          mvn clean install
          cd ..

      # Build + Test + Ba-dua
      - name: Build and analyze
        run: mvn -B clean verify -Pbadua-coverage -Dmaven.test.failure.ignore=true
        
      # Installa xmllint e xmlstarlet  
      - name: Install XML tools
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils xmlstarlet  
        
      # Formatta il report e riducilo alla classe ObjectReader
      - name: Filter Ba-dua report for ObjectReader
        run: |
          cd storm-client

          input_file="badua.xml"
          modified_file="badua_pretty.xml"
          object_reader_class="org/apache/storm/utils/ObjectReader"

          xmllint --format target/$input_file > target/$modified_file
          cp target/$modified_file target/badua_ObjectReader.xml

          xmlstarlet ed -L -d \
            "//class[not(contains(@name, '$object_reader_class'))]" \
            target/badua_ObjectReader.xml  

      # Carica l'artifact per ObjectReader
      - name: Upload ObjectReader report
        uses: actions/upload-artifact@v4
        with:
          name: Ba-dua_ObjectReader_Report
          path: storm-client/target/badua_ObjectReader.xml
          if-no-files-found: error

      # Formatta il report e riducilo alla classe ConfigUtils
      - name: Filter Ba-dua report for ConfigUtils
        run: |
          cd storm-client

          input_file="badua.xml"
          modified_file="badua_pretty.xml"
          config_utils_class="org/apache/storm/utils/ConfigUtils"

          xmllint --format target/$input_file > target/$modified_file
          cp target/$modified_file target/badua_ConfigUtils.xml

          xmlstarlet ed -L -d \
            "//class[not(contains(@name, '$config_utils_class'))]" \
            target/badua_ConfigUtils.xml

      # Carica l'artifact per ConfigUtils
      - name: Upload ConfigUtils report
        uses: actions/upload-artifact@v4
        with:
          name: Ba-dua_ConfigUtils_Report
          path: storm-client/target/badua_ConfigUtils.xml
          if-no-files-found: error
      