name: Pit

on:
  push:
    branches: [ testing-exam ]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      # Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Java 19
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 19

      # Cache Maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build + Test + Pit
      - name: Build and analyze
        run: mvn -B clean verify -Ppit-mutation
      
      # Carica l'artifact      
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: Pit_Report
          path: storm-client/target/pit-reports
          if-no-files-found: error
